// Do not edit. This file is machine generated by the Resource DLL Wizard.

library RDPWInst;

{ITE} {RCFileType} {C\Users\bobo\Downloads\rdpwrap-master\rdpwrap-master\bin\RDPWInst_DRC.rc}

{$R 'C\Users\bobo\Downloads\rdpwrap-master\rdpwrap-master\bin\RDPWInst_DRC.res' 'C\Users\bobo\Downloads\rdpwrap-master\rdpwrap-master\bin\RDPWInst_DRC.rc'}

{$E CHS}

begin
end.
